export const STORAGE_KEYS = {
  USER: 'USER',
  THEME: 'THEME',
  LANGUAGE: 'LANGUAGE',
  ONBOARDING: 'ONBOARDING',
  TOPIC_13_TEXT: 'TOPIC_13_TEXT',
  TOPIC_13_SECURE_TEXT: 'TOPIC_13_SECURE_TEXT',
};

export const SECURE_KEYS = {
  TOPIC_13_SECURE_TEXT: 'TOPIC_13_SECURE_TEXT',
};
