// src/constants/RouteNames.ts

export const RouteNames = {
  INDEX: 'Index',
  LEARNING_TOPIC_1: 'LearningTopic1',
  LEARNING_TOPIC_2: 'LearningTopic2',
  LEARNING_TOPIC_3: 'LearningTopic3',
  LEARNING_TOPIC_4: 'LearningTopic4',
  LEARNING_TOPIC_5: 'LearningTopic5',
  LEARNING_TOPIC_6: 'LearningTopic6',
  LEARNING_TOPIC_7: 'LearningTopic7',
  LEARNING_TOPIC_8: 'LearningTopic8',
  LEARNING_TOPIC_9: 'LearningTopic9',
  LEARNING_TOPIC_10: 'LearningTopic10',
  LEARNING_TOPIC_11: 'LearningTopic11',
  LEARNING_TOPIC_12: 'LearningTopic12',
  LEARNING_TOPIC_13: 'LearningTopic13',
  LEARNING_TOPIC_14: 'LearningTopic14',
  LEARNING_TOPIC_15: 'LearningTopic15',
  LEARNING_TOPIC_16: 'LearningTopic16',
  LEARNING_TOPIC_17: 'LearningTopic17',
  LEARNING_TOPIC_18: 'LearningTopic18',
  LEARNING_TOPIC_19: 'LearningTopic19',
  LEARNING_TOPIC_20: 'LearningTopic20',
  LEARNING_TOPIC_21: 'LearningTopic21',
  LEARNING_TOPIC_22: 'LearningTopic22',
  LEARNING_TOPIC_23: 'LearningTopic23',
  LEARNING_TOPIC_24: 'LearningTopic24',
  TAMAGUI_UI: 'TAMAGUI_UI',
} as const;
